### ISSUE TITLE
Fails to build on ubuntu 14.04

### ISSUE THREAD

**Issue by jeremysalwen** [Andersbakken/rtags#1051]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
Downloading rtags-2.14, running `cmake .` and `make` fails with a C++ compilation error

#### Expected behavior
I expected rtags to compile successfully

#### Actual behavior
`src/ClangIndexer.cpp:476:17: error: 'RCT_FALL_THROUGH' was not declared in this scope.`

This is occurring for me in version 2.14, 2.13, 2.12 and master, compiling with clang 3.8, 3.9, and gcc 4.8

Searching the complete unpacked tarball shows that this symbol is not defined anywhere.  This seems like a bug?  I would expect it would be defined somewhere in RCT, but it's not.

### Environment
- Your operating system:
 Ubuntu 14.04
- LLVM/Clang version:
3.9
### Feature request
Not a feature request

**Comment by Andersbakken** [comment]
I believe your rct submodule needs to be updated.

Can you do a:

git submodule update

and see if that fixes it?

Anders

**Comment by ideasman42** [comment]
I had the error on ArchLinux, updating submodules fixed.

**Comment by jeremysalwen** [comment]
Note that this error is occurring with the release tarball https://andersbakken.github.io/rtags-releases/rtags-2.14.tar.bz2

For which git submodule should not be relevant.

I was able to successfully build master this way though.  I will see if that works with the version in melpa (The root of this error was rtags-install failing)

**Comment by Andersbakken** [comment]
Ah. I see. My new release script doesn't update the submodules :-)

Should be fixed now.

Thanks

Anders

**Comment by jclosure** [comment]
Yep, updating the submodule fixed it.

```git submodule update --init --recursive```

**Comment by Yevgnen** [comment]
Same on macOS 10.12 with llvm 5.0.0.

**Comment by myrgy** [comment]
same for me - fedora 25 / clang 3.9 - release tarball

**Comment by Andersbakken** [comment]
Sorry about the delay guys.

Should work again now.

Anders
