### ISSUE TITLE
Compilation fails on master

### ISSUE THREAD

**Issue by haji-ali** [Andersbakken/rtags#1304]
**Describe the bug**
I get the error

```
"rtags/src/RTags.cpp:797:29: error: ‘clang_Cursor_getNumTemplateArguments’ was not 
declared in this scope                                                                                 
                         if (clang_Cursor_getNumTemplateArguments(cursor) != -1) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
```
**To Reproduce**
Pull latest version of rtags and compile

**Comment by k53sc** [comment]
I ran in the same issue and I guess you are using clang 3.4 too 

https://github.com/Andersbakken/rtags/commit/484c44ad1684a30ca14a0f498dd970846509ba0b 
fixed some issues without making sure if the code would compile on clang 3.4


As a workaround to make sure code is build-able on clang 3.4 I have removed the following snippet completely. ( lines 794 - 811 )

```
                if (!(fileFlags & IndexDataMessage::Visited)) {
                    templateOnly = true;
                    f |= Diagnostic::TemplateOnly;
                    CXCursor cursor = cursorAt(u, diagLoc);
                    bool found = false;
                    do {
                        if (clang_Cursor_getNumTemplateArguments(cursor) != -1) {
found = true;
                            break;
                        }
                        cursor = clang_getCursorSemanticParent(cursor);
                    } while (!clang_isInvalid(clang_getCursorKind(cursor)));

                    if (!found) {
                        // error() << "Ditching diagnostic since we didn't index this file and it doesn't appear to be in a template function"
                        //         << createLocation(diagLoc) << cursorAt(u, diagLoc) << "for" << Location::path(sourceFileId())
                        //         << RTags::eatString(clang_getDiagnosticSpelling(diag));
                        clang_disposeDiagnostic(diag);
                        continue;
                    }
                }
```

I am able to build after this.
Hope that would work for you also.

**Comment by haji-ali** [comment]
That is indeed the case. I have clang 3.4
Does removing this snippet break anything?

**Comment by k53sc** [comment]
I haven't seen any issues build/run time after removing the snippet.

**Comment by Andersbakken** [comment]
This is actually finally fixed. Sorry about the long delay.
