### ISSUE TITLE
Compilation fails due to missing clang-c/Index.h

### ISSUE THREAD

**Issue by shaleh** [Andersbakken/rtags#983]
### Please mark appropriate
 - [x] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
The dependency checker finds the clang libs but does not check for the existence of the clang headers.

#### Expected behavior
The configuration step should fail if the clang headers are not found.

#### Actual behavior
cmake says it found libCLang which it did. However, I did not have the libclang-dev package installed. So the compilation immediately failed.

### Environment
- Your operating system:
Ubuntu 16.04

- LLVM/Clang version:
3.8

### Feature request

Describe the feature we should add to **RTags**.

**Comment by y-ates** [comment]
I can confirm this. It won't compile due to "clang-c/Index.h" for me either.

**Comment by y-ates** [comment]
It seems like the default path was a mess. I simply copied the whole directory 
```/usr/lib/llvm-3.5/include/clang-c```  to  ```/usr/include/clang-c```.
So:
```sudo cp -R /usr/lib/llvm-3.5/include/clang-c /usr/include/```
solved it for me.

OS: Debian 8

**Comment by shaleh** [comment]
All I had to do was ``apt-get install libclang-3.8-dev`` and the build worked. Moving things around is pretty much guaranteed to hork your system @y-ates.

It is common in configure scripts to check for the library to verify runtime functionality and for the header to verify the ability to build. This is just an over sight.

**Comment by shaleh** [comment]
Why was this closed? The configuration script is not doing its job.

**Comment by Andersbakken** [comment]
Oops. I thought you  said that when you installed libclang-3.8-dev. I guess I agree that the findlibclang thing could detect this though. I added something that I think should take care of this now.

**Comment by shaleh** [comment]
Thanks  @Andersbakken

**Comment by fleimgruber** [comment]
I see the same error on Debian Stretch with `libclang-3.8-dev` installed.

**Comment by piojanu** [comment]
Hi!

I got the same problem on Ubuntu 17.10. Even copying `clang-c` to `/usr/local` doesn't help.

Here is CMakeError.log:
```
Performing C++ SOURCE FILE Test LIBCLANG_COMPILES failed with the following output:
Change Dir: /home/piotr/Programs/rtags/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c2b68/fast"
/usr/bin/make -f CMakeFiles/cmTC_c2b68.dir/build.make CMakeFiles/cmTC_c2b68.dir/build
make[1]: Entering directory '/home/piotr/Programs/rtags/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_c2b68.dir/src.cxx.o
/usr/bin/c++    -I/usr/lib/llvm-4.0/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DLIBCLANG_COMPILES  -I/usr/lib/llvm-4.0/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS   -o CMakeFiles/cmTC_c2b68.dir/src.cxx.o -c /home/piotr/Programs/rtags/CMakeFiles/CMakeTmp/src.cxx
/home/piotr/Programs/rtags/CMakeFiles/CMakeTmp/src.cxx:2:10: fatal error: clang-c/Index.h: No such file or directory
 #include <clang-c/Index.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_c2b68.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_c2b68.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_c2b68.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/piotr/Programs/rtags/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c2b68/fast' failed
make: *** [cmTC_c2b68/fast] Error 2

Source file was:

#include <clang-c/Index.h>

int main()
{
    CXIndex index = clang_createIndex(0, true);
    CXTranslationUnit unit = clang_parseTranslationUnit(index, 0, 0, 0, 0, 0, 0);
    clang_disposeTranslationUnit(unit);
    clang_disposeIndex(index);
    return 0;
}
```

I got `clang-c` in `/usr/lib/llvm-4.0/include`.
Shouldn't `#include <clang-c/Index.h>` be `#include "clang-c/Index.h"`?

Thanks for help!

**Comment by piojanu** [comment]
I started fresh and everything worked this time. I don't know how :/ Sorry for digging this thread up.

**Comment by Andersbakken** [comment]
No worries. Glad it worked this time.

Anders

On Fri, Feb 2, 2018 at 11:53 PM, Piotr Januszewski <notifications@github.com

**Comment by manushkin** [comment]
I had the same problem.
The reason is cmake caching. If you install `libclang-3.8-dev` after "CMake Error at src/CMakeLists.txt:90", you need clean cmake cache:

`rm CMakeCache.txt`.

**Comment by Andersbakken** [comment]
Yeah. It's kind of a frustrating thing about cmake. I wish they didn't
cache what amounts to be fatal errors personally.

**Comment by ashrasmun** [comment]
Should I open new **Issue** if I have the same problem but on different OS? I see that you linux-boys can download some libclang-dev package for your system, but I cannot find out how to do such thing on Windows. :(

I have clang tools built from the newest sources (version 9.0.0).

**Comment by Andersbakken** [comment]
I'm afraid RTags currently doesn't work on Windows. There's been some
efforts made to port it by various people but it's still very much
unfinished.

Sorry about that.

Anders

**Comment by alfons4966** [comment]
I am afraid it doesn't work on my Ubuntu 18.04 VM either:

From ~/repos/rtags/CMakeFiles/CMakeError.log

/usr/bin/c++    -Wzero-as-null-pointer-constant -I/usr/lib/llvm-6.0/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DLIBCLANG_COMPILES  -Wzero-as-null-pointer-constant -I/usr/lib/llvm-6.0/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS   -o CMakeFiles/cmTC_a7180.dir/src.cxx.o -c /home/anton/repos/rtags/CMakeFiles/CMakeTmp/src.cxx
/home/anton/repos/rtags/CMakeFiles/CMakeTmp/src.cxx:2:10: fatal error: clang-c/Index.h: No such file or directory
 #include <clang-c/Index.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_a7180.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_a7180.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_a7180.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/anton/repos/rtags/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_a7180/fast' failed
make: *** [cmTC_a7180/fast] Error 2

The problem seems to be that CMake wants to use: **c++** (C++ --version: c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0) instead of **clang++** (clang++ --version: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final) Target: x86_64-pc-linux-gnu Thread model: posix InstalledDir: /usr/bin.) and always uses **c++** even when the preferred CXX compiler is set to clang++ with "sudo update-alternatives --config c++" or the env CXX variable is defined with "CXX=/usr/bin/clang++ && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ."

**Comment by cslux** [comment]
clang-c/Index.h is part of the libclang devel package. See e.g. https://ubuntu.pkgs.org/18.04/ubuntu-updates-universe-amd64/libclang-8-dev_8-3~ubuntu18.04.1_amd64.deb.html and https://packages.ubuntu.com/search?keywords=libclang&searchon=names&suite=bionic&section=all

Also make sure to wipe the cache before running cmake again.

**Comment by lachlanA** [comment]
Would appear to be a problem with clang, include path,
on my Debian  9,  the  <clang-c/Index.h> can be found in...  
 ./lib/llvm-7/include/clang-c/Index.h
 ./lib/llvm-10/include/clang-c/Index.h
 ./lib/llvm-3.8/include/clang-c/Index.h

But the include search path passed to clang with -v is
 /usr/local/include
 /usr/lib/llvm-10/lib/clang/10.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
As you can see no way it will find the Index.h  with a include path like that.

First make sure your **llvm-config** is linking to the correct version of llvm-config, I had this problem
having a number of versions install, and it was link to the wrong version.

 /usr/bin/llvm-config -> ../lib/llvm-10/bin/llvm-config

Do this fixed my problem. 

Lachlan
