### ISSUE TITLE
Does not work on Clang 3.5 any more? (2)

### ISSUE THREAD

**Issue by velkyel** [Andersbakken/rtags#673]
after:
```
$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_EXPORT_COMMANDS=1 .
```
on debian jessie, clang3.5 compilation failed on:

```
[  7%] Building CXX object src/CMakeFiles/rtags.dir/ClangThread.cpp.o
In file included from /home/lcap/rtags/src/ClangThread.cpp:21:0:
/home/lcap/rtags/src/AST.h: In member function 'std::string AST::Cursor::mangledName() const':
/home/lcap/rtags/src/AST.h:109:66: error: 'clang_Cursor_getMangling' was not declared in this scope
         std::string mangledName() const { return stringProperty(&clang_Cursor_getMangling); }
                                                                  ^
/home/lcap/rtags/src/AST.h: In member function 'unsigned int AST::Cursor::templateArgumentCount() const':
/home/lcap/rtags/src/AST.h:159:113: error: 'clang_Cursor_getNumTemplateArguments' was not declared in this scope
         unsigned templateArgumentCount() const { return data ? clang_Cursor_getNumTemplateArguments(data->cursor) : 0; }
                                                                                                                 ^
In file included from /home/lcap/rtags/src/ClangThread.cpp:21:0:
/home/lcap/rtags/src/AST.h: In member function 'AST::CursorType AST::Cursor::templateArgumentType(unsigned int) const':
/home/lcap/rtags/src/AST.h:160:153: error: 'clang_Cursor_getTemplateArgumentType' was not declared in this scope
         CursorType templateArgumentType(unsigned idx) const { return data ? CursorType(data->ast, clang_Cursor_getTemplateArgumentType(data->cursor, idx)) : CursorType(); }
                                                                                                                                                         ^
/home/lcap/rtags/src/AST.h: In member function 'long long int AST::Cursor::templateArgumentValue(unsigned int) const':
/home/lcap/rtags/src/AST.h:161:132: error: 'clang_Cursor_getTemplateArgumentValue' was not declared in this scope
         long long templateArgumentValue(unsigned idx) const { return data ? clang_Cursor_getTemplateArgumentValue(data->cursor, idx) : -1; }
```

**Comment by cslux** [comment]
Hey @velkyel, sorry for the late replay. Should work again, and thanks for the report.

regards,
Christian
