### ISSUE TITLE
rct doesn't compile on OSX 64 bit, LLVM 3.6.1

### ISSUE THREAD

**Issue by adireini** [Andersbakken/rtags#360]
In file included from /Users/adir/src/rtags/src/rct/rct/AES256CBC.cpp:3:
/Users/adir/src/rtags/src/rct/rct/Log.h:122:9: error: class member cannot be redeclared
    Log operator<<(unsigned long long number) { return addStringStream(number); }
        ^
/Users/adir/src/rtags/src/rct/rct/Log.h:119:9: note: previous declaration is here
    Log operator<<(uint64_t number) { return addStringStream(number); }
        ^
/Users/adir/src/rtags/src/rct/rct/Log.h:123:9: error: class member cannot be redeclared
    Log operator<<(long long number) { return addStringStream(number); }
        ^
/Users/adir/src/rtags/src/rct/rct/Log.h:120:9: note: previous declaration is here
    Log operator<<(int64_t number) { return addStringStream(number); }
        ^
/Users/adir/src/rtags/src/rct/rct/Log.h:122:9: error: redefinition of 'operator<<'
    Log operator<<(unsigned long long number) { return addStringStream(number); }
        ^
/Users/adir/src/rtags/src/rct/rct/Log.h:119:9: note: previous definition is here
    Log operator<<(uint64_t number) { return addStringStream(number); }
        ^
/Users/adir/src/rtags/src/rct/rct/Log.h:123:9: error: redefinition of 'operator<<'
    Log operator<<(long long number) { return addStringStream(number); }
        ^
/Users/adir/src/rtags/src/rct/rct/Log.h:120:9: note: previous definition is here
    Log operator<<(int64_t number) { return addStringStream(number); }
        ^

**Comment by Andersbakken** [comment]
Thanks. Should work now.
