### ISSUE TITLE
Does not work on Clang 3.5 any more?

### ISSUE THREAD

**Issue by xuhdev** [Andersbakken/rtags#664]
I have this error:

    /home/hong/.emacs.d/el-get/rtags/src/RTags.h:755:32: error: ‘CXTemplateArgumentKind’ has not been declared
    inline Log operator<<(Log dbg, CXTemplateArgumentKind kind)

I'm currently on Debian Jessie, which distributes clang 3.5. Either the readme (which claims supporting clang 3.5) or some workaround should be applied... I personally wish that clang 3.5 can be supported for a longer time, even by potentially disabling some features in rtags.

**Comment by xuhdev** [comment]
The culprit commit is 24f6b75aeb955218c5c123f8b332309c202dec5f

**Comment by Andersbakken** [comment]
Thanks. Should be fixed now. Can you verify?

**Comment by xuhdev** [comment]
New error:

```
/home/hong/.emacs.d/el-get/rtags/src/RTags.h: In function ‘Log operator<<(Log, CXCallingConv)’:
/home/hong/.emacs.d/el-get/rtags/src/RTags.h:823:10: error: ‘CXCallingConv_X86VectorCall’ was not declared in this scope
     case CXCallingConv_X86VectorCall: dbg << "X86VectorCall"; break;
```

**Comment by Andersbakken** [comment]
I've added something for this too. Can you check if we get further :-)

Anders

**Comment by xuhdev** [comment]
Works now, thanks!
